DEFAULT_USERNAME="teddy"
DEFAULT_HOSTNAME="archbox"
DEFAULT_USE_LUKS="no"
DEFAULT_CPU_DRIVER="auto"
DEFAULT_GPU_DRIVER="auto"
DEFAULT_PACKAGE_LIST=""
MIRRORLIST="https://geo.mirror.pkgbuild.com/$repo/os/$arch"
