DEFAULT_USERNAME="teddy"
DEFAULT_HOSTNAME="archbox"
DEFAULT_USE_LUKS="no"
DEFAULT_CPU_DRIVER="auto"
DEFAULT_GPU_DRIVER="auto"
DEFAULT_PACKAGE_LIST=""
DEFAULT_USER_PASSWORD="arch"
DEFAULT_ROOT_PASSWORD="arch"
MIRRORLIST="https://geo.mirror.pkgbuild.com/$repo/os/$arch"
